# Generated by Django 2.0.7 on 2018-07-22 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0004_checkout_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='created_at',
            new_name='created',
        ),
    ]
