# Generated by Django 2.0.7 on 2018-07-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0005_auto_20180722_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='closed',
            field=models.DateTimeField(blank=True, help_text='When the checkout was closed', null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='saved',
            field=models.DateTimeField(blank=True, help_text='When the checkout was saved', null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='When the checkout was created'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='status',
            field=models.CharField(choices=[('L', 'Launching'), ('O', 'Open'), ('C', 'Closed'), ('F', 'Failed'), ('T', 'Terminated')], help_text='Status of the checkout', max_length=1),
        ),
    ]
