# Generated by Django 2.2.12 on 2020-04-21 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfallback.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0041_auto_20200414_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The time the job was created.', null=True)),
                ('began', models.DateTimeField(help_text='The time the job began.', null=True)),
                ('ended', models.DateTimeField(help_text='The time the job ended.', null=True)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('RECEIVED', 'RECEIVED'), ('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE'), ('REVOKED', 'REVOKED'), ('REJECTED', 'REJECTED'), ('RETRY', 'RETRY')], help_text='The current status of the job.', max_length=32, null=True)),
                ('method', models.CharField(choices=[('pull', 'pull'), ('push', 'push'), ('decode', 'decode'), ('encode', 'encode'), ('convert', 'convert'), ('compile', 'compile'), ('build', 'build'), ('execute', 'execute')], help_text='The job method.', max_length=32)),
                ('params', jsonfallback.fields.FallbackJSONField(blank=True, help_text='The parameters of the job; a JSON object.', null=True)),
                ('result', jsonfallback.fields.FallbackJSONField(blank=True, help_text='The result of the job; a JSON value.', null=True)),
                ('log', jsonfallback.fields.FallbackJSONField(blank=True, help_text='The job log; a JSON array of log objects, including any errors.', null=True)),
                ('url', models.CharField(blank=True, help_text='The URL of the job on the local network; can be used to interact with it.', max_length=256, null=True)),
                ('queue', models.CharField(blank=True, help_text='The identifier of the queue the job was posted to.', max_length=64, null=True)),
                ('worker', models.CharField(blank=True, help_text='The identifier of the worker that ran the job.', max_length=64, null=True)),
                ('retries', models.IntegerField(blank=True, help_text='The number of retries to fulfil the job.', null=True)),
                ('creator', models.ForeignKey(blank=True, help_text='The user who created the job.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='The project this job is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='projects.Project')),
            ],
        ),
    ]
