# Generated by Django 2.2.12 on 2020-04-24 09:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfallback.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0041_auto_20200414_0106'),
        ('django_celery_beat', '0012_periodictask_expire_seconds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0017_auto_20200409_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineSchedule',
            fields=[
                ('periodictask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.PeriodicTask')),
            ],
            bases=('django_celery_beat.periodictask',),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The identifier of the queue the job was posted to.', max_length=256, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9\\-]*$', 'Name should start with a lowercase letter and only contain lowercase letters, digits and hyphens')])),
                ('account', models.ForeignKey(help_text='The account that this zone is linked to.', on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='A name for this pipeline. Must be unique to the project.', max_length=256)),
                ('definition', jsonfallback.fields.FallbackJSONField(help_text='The JSON definition of the pipeline.')),
                ('project', models.ForeignKey(blank=True, help_text='The project this pipeline is linked to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='projects.Project')),
                ('schedule', models.OneToOneField(blank=True, help_text='The schedule for this pipeline.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipeline', to='jobs.PipelineSchedule')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The time the job was created.', null=True)),
                ('queue', models.CharField(blank=True, help_text='The identifier of the queue the job was posted to.', max_length=64, null=True)),
                ('began', models.DateTimeField(help_text='The time the job began.', null=True)),
                ('ended', models.DateTimeField(help_text='The time the job ended.', null=True)),
                ('status', models.CharField(blank=True, choices=[('DISPATCHED', 'DISPATCHED'), ('PENDING', 'PENDING'), ('RECEIVED', 'RECEIVED'), ('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE'), ('REVOKED', 'REVOKED'), ('REJECTED', 'REJECTED'), ('RETRY', 'RETRY'), ('TERMINATED', 'TERMINATED')], help_text='The current status of the job.', max_length=32, null=True)),
                ('method', models.CharField(choices=[('pull', 'pull'), ('push', 'push'), ('decode', 'decode'), ('encode', 'encode'), ('convert', 'convert'), ('compile', 'compile'), ('build', 'build'), ('execute', 'execute')], help_text='The job method.', max_length=32)),
                ('params', jsonfallback.fields.FallbackJSONField(blank=True, help_text='The parameters of the job; a JSON object.', null=True)),
                ('result', jsonfallback.fields.FallbackJSONField(blank=True, help_text='The result of the job; a JSON value.', null=True)),
                ('log', jsonfallback.fields.FallbackJSONField(blank=True, help_text='The job log; a JSON array of log objects, including any errors.', null=True)),
                ('runtime', models.FloatField(blank=True, help_text='The running time of the job.', null=True)),
                ('url', models.CharField(blank=True, help_text='The URL of the job on the local network; can be used to interact with it.', max_length=256, null=True)),
                ('worker', models.CharField(blank=True, help_text='The identifier of the worker that ran the job.', max_length=64, null=True)),
                ('retries', models.IntegerField(blank=True, help_text='The number of retries to fulfil the job.', null=True)),
                ('creator', models.ForeignKey(blank=True, help_text='The user who created the job.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='The project this job is associated with.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='projects.Project')),
                ('users', models.ManyToManyField(help_text='The users who have connected to the job; not necessarily currently connected.', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, help_text='The project this job is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.Zone')),
            ],
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('account', 'name'), name='unique_name'),
        ),
    ]
