# Generated by Django 2.2.12 on 2020-05-15 20:31

from django.db import migrations, models
import django.db.models.deletion
import jsonfallback.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200509_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='error',
            field=jsonfallback.fields.FallbackJSONField(blank=True, help_text='Any error associated with the job; a JSON object with type, message etc.', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The parent job', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='jobs.Job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='method',
            field=models.CharField(choices=[('parallel', 'parallel'), ('series', 'series'), ('chain', 'chain'), ('pull', 'pull'), ('push', 'push'), ('decode', 'decode'), ('encode', 'encode'), ('convert', 'convert'), ('compile', 'compile'), ('build', 'build'), ('execute', 'execute'), ('session', 'session'), ('sleep', 'sleep')], help_text='The job method.', max_length=32),
        ),
        migrations.AlterField(
            model_name='job',
            name='queue',
            field=models.ForeignKey(blank=True, help_text='The queue that this job was routed to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.Queue'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, choices=[('DISPATCHED', 'DISPATCHED'), ('PENDING', 'PENDING'), ('RECEIVED', 'RECEIVED'), ('STARTED', 'STARTED'), ('RUNNING', 'RUNNING'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE'), ('CANCELLED', 'CANCELLED'), ('REVOKED', 'REVOKED'), ('TERMINATED', 'TERMINATED'), ('REJECTED', 'REJECTED'), ('RETRY', 'RETRY')], help_text='The current status of the job.', max_length=32, null=True),
        ),
    ]
