# Generated by Django 3.0.7 on 2020-07-02 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfallback.fields
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=users.models.generate_invite_key, help_text='The key for the invite.', max_length=64, unique=True)),
                ('email', models.EmailField(help_text='The email address of the invitee.', max_length=2048)),
                ('message', models.TextField(blank=True, help_text='An optional message to send to the invitee.', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the invite was created.')),
                ('sent', models.DateTimeField(blank=True, help_text='When the invite was sent.', null=True)),
                ('accepted', models.BooleanField(default=False, help_text='Whether the invite has been accepted or not.')),
                ('completed', models.DateTimeField(blank=True, help_text='When the invite action was completed', null=True)),
                ('action', models.CharField(blank=True, choices=[('join_account', 'Join account'), ('join_team', 'Join team'), ('join_project', 'Join project'), ('take_tour', 'Take tour')], help_text='The action to perform when the invitee signs up.', max_length=64, null=True)),
                ('subject_id', models.IntegerField(blank=True, help_text='The id of the target of the action.', null=True)),
                ('arguments', jsonfallback.fields.FallbackJSONField(blank=True, help_text='Any additional arguments to pass to the action.', null=True)),
                ('inviter', models.ForeignKey(blank=True, help_text='The user who created the invite.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to=settings.AUTH_USER_MODEL)),
                ('subject_type', models.ForeignKey(blank=True, help_text='The type of the target of the action. e.g Team, Account', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
