# Generated by Django 3.0.7 on 2020-07-01 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfallback.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False, verbose_name='accepted')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='key')),
                ('sent', models.DateTimeField(null=True, verbose_name='sent')),
                ('email', models.EmailField(help_text='The email address of the invitee.', max_length=2048)),
                ('created', models.BooleanField(default=False, help_text='Whether or not the invitation action have been completed')),
                ('action', models.CharField(blank=True, choices=[('join_account', 'Join account'), ('join_team', 'Join team'), ('join_project', 'Join project'), ('take_tour', 'Take tour')], help_text='The action to perform when the invitee signs up.', max_length=64, null=True)),
                ('arguments', jsonfallback.fields.FallbackJSONField(blank=True, help_text='Arguments to pass to the action.', null=True)),
                ('message', models.TextField(blank=True, help_text='An optional message to send to the invitee.', null=True)),
                ('inviter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
