# Generated by Django 3.0.8 on 2020-08-04 03:54

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonUser',
            fields=[
                ('id', models.CharField(default=users.models.generate_anonuser_id, help_text='The unique id of the anonymous user.', max_length=64, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The time the anon user was created.')),
            ],
        ),
    ]
