# Generated by Django 3.1.3 on 2020-11-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='action',
            field=models.CharField(blank=True, choices=[('join_account', 'Join account'), ('join_team', 'Join team'), ('join_project', 'Join project'), ('accept_review', 'Accept to review'), ('take_tour', 'Take tour')], help_text='The action to perform when the invitee signs up.', max_length=64, null=True),
        ),
    ]
