# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-12 02:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(help_text='The django.contrib.auth User', on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User details',
                'verbose_name_plural': 'User details',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='01', help_text='Version identifier for the token', max_length=2)),
                ('origin', models.CharField(blank=True, help_text='Origin that this token is valid for', max_length=128, null=True)),
                ('string', models.CharField(blank=True, help_text='The actual token string', max_length=128, null=True)),
                ('name', models.CharField(blank=True, help_text='Name for this token', max_length=32, null=True)),
                ('issued', models.DateTimeField(blank=True, help_text='Date and time that the token was created', null=True)),
                ('expires', models.DateTimeField(blank=True, help_text='Date and time that the token will expire', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the token', null=True)),
                ('user', models.ForeignKey(help_text='The user this token represents', on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
