# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='builder',
            field=models.BooleanField(default=False, help_text='Is this user a package builder?'),
        ),
    ]
