# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 03:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_userdetails_builder'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, help_text='Date/time the event occurred', null=True)),
                ('name', models.CharField(help_text='Name of the event', max_length=128)),
                ('data', jsonfield.fields.JSONField(blank=True, help_text='Data associated with the event', null=True)),
                ('user', models.ForeignKey(help_text='The user this event is linked to', on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
