# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userdetails_tester'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='auto',
            field=models.BooleanField(default=False, help_text='Is this an automatically authenticated user?'),
        ),
    ]
