# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userdetails_auto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='auto',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='guest',
            field=models.BooleanField(default=False, help_text='Is this user a guest?'),
        ),
    ]
