# Generated by Django 3.0.8 on 2020-07-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, help_text='An email to display in account profile. Will not be used by Stencila to contact you.', max_length=254, null=True),
        ),
    ]
