# Generated by Django 3.0.8 on 2020-08-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200721_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttier',
            name='file_downloads_month',
            field=models.FloatField(default=10, help_text='The maximum total size of downloads of project files per month (GB).', verbose_name='File downloads'),
        ),
    ]
