# Generated by Django 3.1 on 2020-08-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_accounttier_file_downloads_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='extra_bottom',
            field=models.TextField(blank=True, help_text='Content to inject at the bottom of the <body> element of HTML served for this account.', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='extra_head',
            field=models.TextField(blank=True, help_text='Content to inject into the <head> element of HTML served for this account.', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='extra_top',
            field=models.TextField(blank=True, help_text='Content to inject at the top of the <body> element of HTML served for this account.', null=True),
        ),
    ]
