# Generated by Django 3.1.3 on 2020-11-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200827_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttier',
            name='dois_created_month',
            field=models.IntegerField(default=0, help_text='The maximum number of DOIs minted per month.', verbose_name='DOIs minted'),
        ),
    ]
