# Generated by Django 3.1.3 on 2020-12-02 03:49

from django.db import migrations
import imagefield.fields
import manager.storage


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_accounttier_dois_created_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=imagefield.fields.ImageField(blank=True, height_field='image_height', help_text='Image for the account.', null=True, storage=manager.storage.FileSystemStorage(base_url='/local/media', location='/home/nokome/stencila/source/hub/manager/../storage/data/media'), upload_to='accounts/images', width_field='image_width'),
        ),
    ]
