# Generated by Django 3.1.5 on 2021-01-27 22:44

from django.db import migrations, models
import django.db.models.deletion
import imagefield.fields
import manager.storage


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0007_2_4'),
        ('accounts', '0008_auto_20201202_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='billing_email',
            field=models.EmailField(blank=True, help_text='The email to use for billing (e.g. sending invoices)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='customer',
            field=models.OneToOneField(default=None, help_text='The Stripe customer instance (if this account has ever been one)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account', to='djstripe.customer'),
        ),
        migrations.AddField(
            model_name='accounttier',
            name='product',
            field=models.OneToOneField(blank=True, help_text='The Stripe product for the account tier.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.product'),
        ),
        migrations.AddField(
            model_name='accounttier',
            name='summary',
            field=models.TextField(help_text='A user facing, summary description of the account tier.', null=True),
        ),
    ]
