# Generated by Django 3.1.5 on 2021-02-03 20:54

from django.db import migrations, models
import django.db.models.deletion
import imagefield.fields
import manager.storage


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0007_2_4'),
        ('accounts', '0009_auto_20210131_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='customer',
            field=models.OneToOneField(blank=True, default=None, help_text='The Stripe customer instance (if this account has ever been one)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account', to='djstripe.customer'),
        ),
    ]
