# Generated by Django 3.1.7 on 2021-03-29 06:06

from django.db import migrations, models
import imagefield.fields
import manager.storage


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210210_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttier',
            name='projects_total',
            field=models.IntegerField(default=200, help_text='The maximum number of projects of all types (public, private, temporary) that an account can have.', verbose_name='Total projects'),
        )
    ]
