# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-12-22 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='pinged',
            field=models.DateTimeField(blank=True, help_text='Time that this session was last pinged by a client', null=True),
        ),
    ]
