# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2016-01-12 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_', '0002_session_pinged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='component',
        ),
        migrations.AlterField(
            model_name='session',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Account that this session is linked to. Usually not null.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='session',
            name='command',
            field=models.CharField(blank=True, default='stencila-session', help_text='Command to run the session in the Docker container', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='cpu',
            field=models.IntegerField(blank=True, default=1024, help_text='CPU share for this session. Share out of 1024', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='image',
            field=models.CharField(default='', help_text='Image for this session', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='memory',
            field=models.CharField(blank=True, default='1g', help_text='Memory limit for this session. Format: <number><optional unit>, where unit = b, k, m or g', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='provider',
            field=models.CharField(choices=[(b'vbox', b'VirtualBox'), (b'local', b'Localhost'), (b'ec2', b'EC2')], help_text='The provider (e.g. Amazon EC2) for the worker', max_length=16, null=True),
        ),
    ]
