# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_', '0003_auto_20160112_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Docker image', max_length=128)),
                ('tag', models.CharField(default='latest', help_text='Tag on the Docker image', max_length=128)),
                ('display_name', models.CharField(help_text='Name of the image as displayed', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SessionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the session type', max_length=128)),
                ('description', models.TextField(help_text='A short description of the session type')),
                ('ram', models.FloatField(default=0, help_text='Gigabytes (GB) of RAM allocated')),
                ('cpu', models.FloatField(default=0, help_text='Gigahertz (GHz) of CPU allocated to the session')),
                ('network', models.FloatField(default=0, help_text='Gigabytes (GB) of netwrk transfer allocated to the session')),
                ('timeout', models.FloatField(default=0, help_text='Minutes of inactivity before the session is terminated')),
            ],
        ),
        migrations.AlterField(
            model_name='session',
            name='image',
            field=models.CharField(help_text='Image name string for this session. Redundant given image_model', max_length=64),
        ),
        migrations.AddField(
            model_name='session',
            name='image_model',
            field=models.ForeignKey(default=1, help_text='SessionImage for this session', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='sessions_.SessionImage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='type',
            field=models.ForeignKey(default=1, help_text='SessionType for this session', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='sessions_.SessionType'),
            preserve_default=False,
        ),
    ]
