# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-20 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_', '0006_auto_20160320_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='cpus',
            field=models.FloatField(default=1, help_text='Number of CPUs/vCPUs'),
        ),
        migrations.AddField(
            model_name='worker',
            name='memory',
            field=models.FloatField(default=1, help_text='Random access memory (RAM) in GB'),
        ),
        migrations.AddField(
            model_name='worker',
            name='storage',
            field=models.FloatField(default=10, help_text='Disk storage in GB'),
        ),
    ]
