# Generated by prepare.js. Commit this file, but do not edit it.

# fmt: off

version = "2.10.4"
themes = [
    "bootstrap",
    "elife",
    "galleria",
    "latex",
    "nature",
    "plos",
    "rpng",
    "skeleton",
    "stencila",
    "tufte",
    "wilmore"
]
