# Generated by prepare.js. Commit this file, but do not edit it.

version = "2.2.0"
themes = [
    "bootstrap",
    "elife",
    "galleria",
    "nature",
    "plos",
    "rpng",
    "skeleton",
    "stencila",
    "wilmore",
]
