# Generated by prepare.js. Commit this file, but do not edit it.

# fmt: off

version = "2.2.6"
themes = [
    "bootstrap",
    "elife",
    "galleria",
    "nature",
    "plos",
    "rpng",
    "skeleton",
    "stencila",
    "wilmore"
]
