/* tslint:disable */
/* eslint-disable */

/**
 * Stencila Hub Typescript Client
 *
 * This file is auto generated by OpenAPI Generator. Do not edit manually.
 */
import { exists, mapValues } from '../runtime';
import {
    User,
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './';

/**
 * 
 * @export
 * @interface AccountUser
 */
export interface AccountUser {
    /**
     * 
     * @type {number}
     * @memberof AccountUser
     */
    readonly id?: number;
    /**
     * 
     * @type {User}
     * @memberof AccountUser
     */
    user: User;
    /**
     * Role the user has within the account.
     * @type {string}
     * @memberof AccountUser
     */
    role: AccountUserRoleEnum;
    /**
     * Account to which the user belongs.
     * @type {number}
     * @memberof AccountUser
     */
    account: number;
}

export function AccountUserFromJSON(json: any): AccountUser {
    return AccountUserFromJSONTyped(json, false);
}

export function AccountUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'user': UserFromJSON(json['user']),
        'role': json['role'],
        'account': json['account'],
    };
}

export function AccountUserToJSON(value?: AccountUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': UserToJSON(value.user),
        'role': value.role,
        'account': value.account,
    };
}

/**
* @export
* @enum {string}
*/
export enum AccountUserRoleEnum {
    Member = 'MEMBER',
    Manager = 'MANAGER',
    Owner = 'OWNER'
}


