/* tslint:disable */
/* eslint-disable */

/**
 * Stencila Hub Typescript Client
 *
 * This file is auto generated by OpenAPI Generator. Do not edit manually.
 */
import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileList
 */
export interface FileList {
    /**
     * 
     * @type {number}
     * @memberof FileList
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof FileList
     */
    readonly name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof FileList
     */
    readonly isDirectory?: boolean;
    /**
     * 
     * @type {number}
     * @memberof FileList
     */
    readonly count?: number;
    /**
     * 
     * @type {string}
     * @memberof FileList
     */
    readonly source?: string;
    /**
     * The path of the file within the project.
     * @type {string}
     * @memberof FileList
     */
    path: string;
    /**
     * Is the file currently in the project? Used to retain a history for file paths within a project.
     * @type {boolean}
     * @memberof FileList
     */
    current?: boolean;
    /**
     * The time the file info was created.
     * @type {Date}
     * @memberof FileList
     */
    readonly created?: Date;
    /**
     * The time the file info was updated. This field will have the last time this row was altered (i.e. changed from current, to not).
     * @type {Date}
     * @memberof FileList
     */
    updated?: Date | null;
    /**
     * The file modification time.
     * @type {Date}
     * @memberof FileList
     */
    modified?: Date | null;
    /**
     * The size of the file in bytes
     * @type {number}
     * @memberof FileList
     */
    size?: number | null;
    /**
     * The mimetype of the file.
     * @type {string}
     * @memberof FileList
     */
    mimetype?: string | null;
    /**
     * The encoding of the file e.g. gzip
     * @type {string}
     * @memberof FileList
     */
    encoding?: string | null;
    /**
     * The fingerprint of the file
     * @type {string}
     * @memberof FileList
     */
    fingerprint?: string | null;
    /**
     * The job that created the file e.g. a source pull or file conversion.
     * @type {number}
     * @memberof FileList
     */
    job?: number | null;
    /**
     * The snapshot that the file belongs. If the snapshot is deleted so will the files.
     * @type {string}
     * @memberof FileList
     */
    snapshot?: string | null;
    /**
     * The files that this file was derived from (if any).
     * @type {Set<number>}
     * @memberof FileList
     */
    upstreams: Set<number>;
}

export function FileListFromJSON(json: any): FileList {
    return FileListFromJSONTyped(json, false);
}

export function FileListFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'isDirectory': !exists(json, 'isDirectory') ? undefined : json['isDirectory'],
        'count': !exists(json, 'count') ? undefined : json['count'],
        'source': !exists(json, 'source') ? undefined : json['source'],
        'path': json['path'],
        'current': !exists(json, 'current') ? undefined : json['current'],
        'created': !exists(json, 'created') ? undefined : (new Date(json['created'])),
        'updated': !exists(json, 'updated') ? undefined : (json['updated'] === null ? null : new Date(json['updated'])),
        'modified': !exists(json, 'modified') ? undefined : (json['modified'] === null ? null : new Date(json['modified'])),
        'size': !exists(json, 'size') ? undefined : json['size'],
        'mimetype': !exists(json, 'mimetype') ? undefined : json['mimetype'],
        'encoding': !exists(json, 'encoding') ? undefined : json['encoding'],
        'fingerprint': !exists(json, 'fingerprint') ? undefined : json['fingerprint'],
        'job': !exists(json, 'job') ? undefined : json['job'],
        'snapshot': !exists(json, 'snapshot') ? undefined : json['snapshot'],
        'upstreams': json['upstreams'],
    };
}

export function FileListToJSON(value?: FileList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'path': value.path,
        'current': value.current,
        'updated': value.updated === undefined ? undefined : (value.updated === null ? null : value.updated.toISOString()),
        'modified': value.modified === undefined ? undefined : (value.modified === null ? null : value.modified.toISOString()),
        'size': value.size,
        'mimetype': value.mimetype,
        'encoding': value.encoding,
        'fingerprint': value.fingerprint,
        'job': value.job,
        'snapshot': value.snapshot,
        'upstreams': value.upstreams,
    };
}


