/* tslint:disable */
/* eslint-disable */

/**
 * Stencila Hub Typescript Client
 *
 * This file is auto generated by OpenAPI Generator. Do not edit manually.
 */
import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectAgent
 */
export interface ProjectAgent {
    /**
     * 
     * @type {number}
     * @memberof ProjectAgent
     */
    readonly id?: number;
    /**
     * Project to which the user or team is being given access to.
     * @type {number}
     * @memberof ProjectAgent
     */
    project: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectAgent
     */
    readonly type?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectAgent
     */
    readonly agent?: string;
    /**
     * Role the user or team has within the project.
     * @type {string}
     * @memberof ProjectAgent
     */
    role: ProjectAgentRoleEnum;
}

export function ProjectAgentFromJSON(json: any): ProjectAgent {
    return ProjectAgentFromJSONTyped(json, false);
}

export function ProjectAgentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectAgent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'project': json['project'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'agent': !exists(json, 'agent') ? undefined : json['agent'],
        'role': json['role'],
    };
}

export function ProjectAgentToJSON(value?: ProjectAgent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'project': value.project,
        'role': value.role,
    };
}

/**
* @export
* @enum {string}
*/
export enum ProjectAgentRoleEnum {
    Reader = 'READER',
    Reviewer = 'REVIEWER',
    Editor = 'EDITOR',
    Author = 'AUTHOR',
    Manager = 'MANAGER',
    Owner = 'OWNER'
}


