/* tslint:disable */
/* eslint-disable */

/**
 * Stencila Hub Typescript Client
 *
 * This file is auto generated by OpenAPI Generator. Do not edit manually.
 */
import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Snapshot
 */
export interface Snapshot {
    /**
     * The unique id of the snapshot.
     * @type {string}
     * @memberof Snapshot
     */
    readonly id?: string;
    /**
     * The number of the snapshot within the project.
     * @type {number}
     * @memberof Snapshot
     */
    readonly number?: number;
    /**
     * The time the snapshot was created.
     * @type {Date}
     * @memberof Snapshot
     */
    readonly created?: Date;
    /**
     * The path of the snapshot's directory within the snapshot storage volume.
     * @type {string}
     * @memberof Snapshot
     */
    path?: string | null;
    /**
     * The name of snapshot's Zip file (within the snapshot directory).
     * @type {string}
     * @memberof Snapshot
     */
    zipName?: string | null;
    /**
     * The user who created the snapshot.
     * @type {number}
     * @memberof Snapshot
     */
    readonly creator?: number;
    /**
     * The job that created the snapshot
     * @type {number}
     * @memberof Snapshot
     */
    readonly job?: number;
}

export function SnapshotFromJSON(json: any): Snapshot {
    return SnapshotFromJSONTyped(json, false);
}

export function SnapshotFromJSONTyped(json: any, ignoreDiscriminator: boolean): Snapshot {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'number': !exists(json, 'number') ? undefined : json['number'],
        'created': !exists(json, 'created') ? undefined : (new Date(json['created'])),
        'path': !exists(json, 'path') ? undefined : json['path'],
        'zipName': !exists(json, 'zipName') ? undefined : json['zipName'],
        'creator': !exists(json, 'creator') ? undefined : json['creator'],
        'job': !exists(json, 'job') ? undefined : json['job'],
    };
}

export function SnapshotToJSON(value?: Snapshot | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'path': value.path,
        'zipName': value.zipName,
    };
}


