/* tslint:disable */
/* eslint-disable */

/**
 * Stencila Hub Typescript Client
 *
 * This file is auto generated by OpenAPI Generator. Do not edit manually.
 */
import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Zone
 */
export interface Zone {
    /**
     * 
     * @type {number}
     * @memberof Zone
     */
    readonly id?: number;
    /**
     * The identifier of the queue the job was posted to.
     * @type {string}
     * @memberof Zone
     */
    name: string;
    /**
     * The account that this zone is linked to.
     * @type {number}
     * @memberof Zone
     */
    account: number;
}

export function ZoneFromJSON(json: any): Zone {
    return ZoneFromJSONTyped(json, false);
}

export function ZoneFromJSONTyped(json: any, ignoreDiscriminator: boolean): Zone {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
        'account': json['account'],
    };
}

export function ZoneToJSON(value?: Zone | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'account': value.account,
    };
}


