# Generated by Django 3.0.6 on 2020-06-11 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The time the project was created.')),
                ('name', models.SlugField(help_text='Name of the project. Lowercase only and unique for the account. Will be used in URLS e.g. https://hub.stenci.la/awesome-org/great-project.')),
                ('title', models.CharField(blank=True, help_text='Title of the project to display in its profile.', max_length=256, null=True)),
                ('public', models.BooleanField(default=True, help_text='Should the project be publicly visible?')),
                ('description', models.TextField(blank=True, help_text='Brief description of the project.', null=True)),
                ('theme', models.TextField(blank=True, help_text='The name of the theme to use as the default when generating content for this project.', null=True)),
                ('account', models.ForeignKey(help_text='Account that the project belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='accounts.Account')),
                ('creator', models.ForeignKey(help_text='The user who created the project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('READER', 'Reader'), ('COMMENTER', 'Commenter'), ('SUGGESTER', 'Suggester'), ('AUTHOR', 'Author'), ('MANAGER', 'Manager'), ('OWNER', 'Owner')], help_text='Role the user or team has within the project.', max_length=32)),
                ('project', models.ForeignKey(help_text='Project to which the user or team is being given access to.', on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='projects.Project')),
                ('team', models.ForeignKey(blank=True, help_text='A team given access to the project.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.AccountTeam')),
                ('user', models.ForeignKey(blank=True, help_text='A user given access to the project.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='projectagent',
            constraint=models.UniqueConstraint(fields=('project', 'user', 'team'), name='unique_project_agent'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('account', 'name'), name='unique_project_name'),
        ),
    ]
