# Generated by Django 3.0.8 on 2020-07-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='url',
        ),
        migrations.AddField(
            model_name='urlsource',
            name='uri',
            field=models.URLField(default='https://example.org', help_text='The URL of the source.'),
            preserve_default=False,
        ),
    ]
