# Generated by Django 3.0.8 on 2020-07-12 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200710_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlsource',
            old_name='uri',
            new_name='url',
        ),
    ]
