# Generated by Django 3.0.8 on 2020-07-20 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200708_2203'),
        ('accounts', '0002_models'),
        ('projects', '0004_add_project_temporary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='account',
            field=models.ForeignKey(help_text='Account that the project belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='job',
            field=models.ForeignKey(blank=True, help_text='The job that created the snapshot', null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.Job'),
        ),
    ]
