# Generated by Django 3.0.8 on 2020-07-22 05:10

from django.db import migrations, models
import projects.models.snapshots


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200720_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='number',
            field=models.IntegerField(db_index=True, default=1, help_text='The number of the snapshot within the project.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='id',
            field=models.CharField(default=projects.models.snapshots.generate_snapshot_id, editable=False, help_text='The unique id of the snapshot.', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='snapshot',
            constraint=models.UniqueConstraint(fields=('project', 'number'), name='snapshot_unique_project_number'),
        ),
    ]
