# Generated by Django 3.0.8 on 2020-07-27 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200722_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='dependencies',
        ),
        migrations.AddField(
            model_name='file',
            name='current',
            field=models.BooleanField(default=True, help_text='Is the file currently in the project? Used to retain a history for file paths within a project.'),
        ),
        migrations.AddField(
            model_name='file',
            name='fingerprint',
            field=models.CharField(blank=True, help_text='The fingerprint of the file', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='upstreams',
            field=models.ManyToManyField(help_text='The files that this file was derived from (if any).', related_name='downstreams', to='projects.File'),
        ),
        migrations.AlterField(
            model_name='file',
            name='source',
            field=models.ForeignKey(blank=True, help_text='The source from which the file came (if any). If the source is removed from the project, so will this file.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.Source'),
        ),
        migrations.AlterField(
            model_name='file',
            name='updated',
            field=models.DateTimeField(blank=True, help_text='The time the file info was updated. This field will have the last time this row was altered (i.e. changed from current, to not).', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='main',
            field=models.TextField(blank=True, help_text='Path of the main file of the project', null=True),
        ),
    ]
