# Generated by Django 3.0.8 on 2020-07-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200727_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsource',
            name='content_type',
            field=models.TextField(blank=True, help_text='The content type (MIME type) of the uploaded file.', null=True),
        ),
        migrations.AddField(
            model_name='uploadsource',
            name='name',
            field=models.TextField(blank=True, help_text='The name of the uploaded file.', null=True),
        ),
        migrations.AddField(
            model_name='uploadsource',
            name='size',
            field=models.IntegerField(blank=True, help_text='The size of the uploaded file in bytes.', null=True),
        ),
    ]
