# Generated by Django 3.0.8 on 2020-08-04 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20200804_0354'),
        ('projects', '0009_auto_20200727_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='job',
            field=models.ForeignKey(blank=True, help_text='The job that created the snapshot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshot_created', to='jobs.Job'),
        ),
    ]
