# Generated by Django 3.0.8 on 2020-08-06 06:05

from django.db import migrations, models
import django.db.models.deletion
import projects.models.projects


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20200804_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='key',
            field=models.CharField(default=projects.models.projects.generate_project_key, help_text='A unique, and very difficult to guess, key to access this project if it is not public.', max_length=64),
        ),
        migrations.AddField(
            model_name='project',
            name='liveness',
            field=models.CharField(choices=[('latest', 'Use latest snapshot'), ('pinned', 'Pinned to snapshot')], default='latest', help_text='Where to serve the content for this project from.', max_length=16),
        ),
        migrations.AddField(
            model_name='project',
            name='pinned',
            field=models.ForeignKey(blank=True, help_text='If pinned, the snapshot to pin to, when serving content.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_pinned', to='projects.Snapshot'),
        ),
    ]
