# Generated by Django 3.1 on 2020-08-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20200807_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='extra_bottom',
            field=models.TextField(blank=True, help_text='Content to inject at the bottom of the <body> element of HTML served for this project.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='extra_head',
            field=models.TextField(blank=True, help_text='Content to inject into the <head> element of HTML served for this project.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='extra_top',
            field=models.TextField(blank=True, help_text='Content to inject at the top of the <body> element of HTML served for this project.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='liveness',
            field=models.CharField(choices=[('live', 'Use working directory'), ('latest', 'Use latest snapshot'), ('pinned', 'Pinned to snapshot')], default='latest', help_text='Where to serve the content for this project from.', max_length=16),
        ),
    ]
