# Generated by Django 3.1.2 on 2020-10-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='container_image',
            field=models.TextField(blank=True, help_text='The container image to use as the execution environment for this project.', null=True),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='container_image',
            field=models.TextField(blank=True, help_text='The container image to use as the execution environment for this snapshot.', null=True),
        ),
    ]
