# Generated by Django 3.1.2 on 2020-10-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20201007_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googledrivesource',
            name='folder_id',
        ),
        migrations.AddField(
            model_name='googledrivesource',
            name='google_id',
            field=models.TextField(default='', help_text='The id of the file or folder.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='googledrivesource',
            name='kind',
            field=models.CharField(choices=[('file', 'File'), ('folder', 'Folder')], default='folder', help_text='The kind of Google Drive resource: file or folder.', max_length=16),
            preserve_default=False,
        ),
    ]
