# Generated by Django 3.1.2 on 2020-10-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20201019_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='path',
            field=models.TextField(blank=True, help_text='The file or folder name, or path, that the source is mapped to.', null=True),
        ),
    ]
