# Generated by Django 3.1.3 on 2020-11-08 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20201023_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheetsSource',
            fields=[
                ('googledocssource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.googledocssource')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('projects.googledocssource',),
        ),
    ]
