# Generated by Django 3.1.3 on 2020-12-02 03:49

from django.db import migrations, models
import manager.storage
import projects.models.sources


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_description',
            field=models.TextField(blank=True, help_text='The description of the review.', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='review_title',
            field=models.TextField(blank=True, help_text='The title of the review.', null=True),
        ),
        migrations.AlterField(
            model_name='uploadsource',
            name='file',
            field=models.FileField(help_text='The uploaded file.', storage=manager.storage.FileSystemStorage(base_url='/local/uploads', location='/home/nokome/stencila/source/hub/manager/../storage/data/uploads'), upload_to=projects.models.sources.upload_source_path),
        ),
    ]
