# Generated by Django 3.1.4 on 2020-12-11 23:19

from django.db import migrations, models
import manager.storage


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20201206_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_file',
            field=models.ImageField(blank=True, help_text='The image used for this project in project listings and HTML meta data.', null=True, storage=manager.storage.FileSystemStorage(base_url='/local/media', location='/home/nokome/stencila/source/hub/manager/../storage/data/media'), upload_to='projects/images'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_path',
            field=models.CharField(blank=True, help_text="Path of file in the project's working directory to use as this project's image. Allows the project's image to update as it is re-executed.", max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image_updated',
            field=models.DateTimeField(blank=True, help_text='When the image file was last updated (e.g. from image_path).', null=True),
        ),
    ]
