# Generated by Django 3.1.4 on 2020-12-10 03:12

from django.db import migrations, models
import manager.storage


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20201206_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_path',
            field=models.CharField(blank=True, help_text="Path of image in the project's working directory to use for this project. Allows the project's image to update as it is re-executed.", max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image_static',
            field=models.ImageField(blank=True, help_text='The static image used for this project in project listings and HTML meta data.', null=True, storage=manager.storage.FileSystemStorage(base_url='/local/media', location='/home/nokome/stencila/source/hub/manager/../storage/data/media'), upload_to='projects/images'),
        ),
    ]
