# Generated by Django 3.1.4 on 2020-12-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20201211_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False, help_text='Is the project to be featured in listings?'),
        ),
    ]
