# Generated by Django 3.1.5 on 2021-02-03 20:54

from django.db import migrations, models
import manager.storage
import projects.models.sources


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_project_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upstreams',
            field=models.ManyToManyField(blank=True, help_text='The files that this file was derived from (if any).', related_name='downstreams', to='projects.File'),
        )
    ]
