# Generated by Django 3.1.6 on 2021-02-10 23:40

from django.db import migrations, models
import manager.storage
import projects.models.sources


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_auto_20210210_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='session_memory',
            field=models.PositiveIntegerField(blank=True, help_text='The amount of memory allocated (request and limit) for a session (MiB).', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='session_timelimit',
            field=models.PositiveIntegerField(blank=True, help_text='The maximum duration of a session (s).', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='session_timeout',
            field=models.PositiveIntegerField(blank=True, help_text='The amount of time of inactivity after which a session will end (s).', null=True),
        )
    ]
