# Generated by Django 3.1.7 on 2021-03-15 22:30

from django.db import migrations, models
import django.db.models.deletion
import manager.storage
import projects.models.sources


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('projects', '0029_auto_20210210_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='googledocssource',
            name='social_app',
            field=models.ForeignKey(blank=True, help_text='The OAuth client that this Google Doc was linked using.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialaccount.socialapp'),
        ),
    ]
