# Generated by Django 3.0.7 on 2020-06-24 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='project',
            field=models.ForeignKey(blank=True, help_text='The project this pipeline is linked to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='schedule',
            field=models.OneToOneField(blank=True, help_text='The schedule for this pipeline.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipeline', to='jobs.PipelineSchedule'),
        ),
        migrations.AddField(
            model_name='job',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='The user who created the job.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The parent job', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='jobs.Job'),
        ),
        migrations.AddField(
            model_name='job',
            name='project',
            field=models.ForeignKey(blank=True, help_text='The project this job is associated with.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='job',
            name='queue',
            field=models.ForeignKey(blank=True, help_text='The queue that this job was routed to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.Queue'),
        ),
        migrations.AddField(
            model_name='job',
            name='users',
            field=models.ManyToManyField(help_text='The users who have connected to the job; not necessarily currently connected.', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('account', 'name'), name='unique_name'),
        ),
    ]
