# Generated by Django 3.0.8 on 2020-07-29 08:53

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200723_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='key',
            field=models.CharField(default=jobs.models.generate_job_key, help_text='A unique, and very difficult to guess, key to access the job with.', max_length=64),
        ),
    ]
