# Generated by Django 3.0.8 on 2020-08-04 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20200727_2346'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_anonuser'),
        ('jobs', '0004_job_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='anon_users',
            field=models.ManyToManyField(help_text='Anonymous users who have created or connected to the job.', to='users.AnonUser'),
        ),
        migrations.AddField(
            model_name='job',
            name='snapshot',
            field=models.ForeignKey(blank=True, help_text='The snapshot that this job is associated with.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='projects.Snapshot'),
        ),
        migrations.AlterField(
            model_name='job',
            name='users',
            field=models.ManyToManyField(help_text='Users who have created or connected to the job; not necessarily currently connected.', to=settings.AUTH_USER_MODEL),
        ),
    ]
