# Generated by Django 3.0.8 on 2020-08-06 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20200806_0605'),
        ('jobs', '0005_auto_20200804_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='snapshot',
            field=models.ForeignKey(blank=True, help_text='The snapshot that this job is associated with. Usually `session` jobs for the snapshot.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='projects.Snapshot'),
        ),
    ]
