# Generated by Django 3.1.2 on 2020-10-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20201007_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='url',
        ),
        migrations.AddField(
            model_name='job',
            name='urls',
            field=models.JSONField(blank=True, help_text='The URLs of the job on the local network (by protocol); can be used to interact with it.', null=True),
        ),
    ]
