# Generated by Django 3.1.3 on 2020-11-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20201112_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='method',
            field=models.CharField(choices=[('parallel', 'parallel'), ('series', 'series'), ('chain', 'chain'), ('clean', 'clean'), ('archive', 'archive'), ('pull', 'pull'), ('push', 'push'), ('extract', 'extract'), ('decode', 'decode'), ('encode', 'encode'), ('convert', 'convert'), ('pin', 'pin'), ('register', 'register'), ('compile', 'compile'), ('build', 'build'), ('execute', 'execute'), ('session', 'session'), ('sleep', 'sleep')], help_text='The job method.', max_length=32),
        ),
    ]
