# Generated by Django 3.1.7 on 2021-02-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20210214_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='secrets',
            field=models.JSONField(blank=True, help_text='Any secrets (e.g. API tokens) required to perform the job. When the job has ended these should be deleted.', null=True),
        ),
    ]
