# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2016-01-13 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='shown',
            new_name='published',
        ),
        migrations.AlterField(
            model_name='component',
            name='published',
            field=models.BooleanField(default=False, help_text='Should this component be published in listings of components at an address?'),
        ),
    ]
