# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_auto_20160113_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='action',
            field=models.IntegerField(choices=[(0, 'NONE'), (10, 'READ'), (15, 'EXECUTE'), (20, 'ANNOTATE'), (30, 'UPDATE'), (40, 'AUTHORIZE'), (50, 'DELETE'), (60, 'CREATE')], help_text='The access right granted by this key to a component.'),
        ),
    ]
