# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 23:16
from __future__ import unicode_literals

import components.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='file',
            field=models.FileField(blank=True, help_text='File (.tar.gz) for this snapshot', null=True, storage=django.core.files.storage.FileSystemStorage, upload_to=components.models.snapshot_upload_to),
        ),
    ]
