# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 23:58
from __future__ import unicode_literals

import components.models
from django.db import migrations, models
import general.custom_storages


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_auto_20160308_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='file',
            field=models.FileField(blank=True, help_text='File (.tar.gz) for this snapshot', null=True, storage=general.custom_storages.SnapshotsFileSystemStorage(), upload_to=components.models.snapshot_upload_to),
        ),
    ]
