# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-20 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_auto_20160308_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='type',
            field=models.CharField(blank=True, choices=[('address', 'Address'), ('session', 'Session'), ('sheet', 'Sheet'), ('stencil', 'Stencil'), ('theme', 'Theme')], help_text='The type of component or resource this key gives access rights to.If blank, gives access to all types of component.', max_length=32, null=True),
        ),
    ]
