# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-11 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0008_auto_20160320_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='environ',
            field=models.CharField(blank=True, help_text='The type of execution environment for this component.', max_length=128, null=True),
        ),
    ]
