# Generated by Django 2.2.4 on 2019-09-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.TextField(help_text='A unique id used when sharing this Conversion.', unique=True)),
                ('input_url', models.URLField(blank=True, help_text='The original URL this content was converted from. Mutually exclusive with source_file.', null=True)),
                ('input_file', models.TextField(blank=True, help_text='The path to the file this content was converted from. Mutually exclusive with source_url', null=True)),
                ('output_file', models.TextField(blank=True, help_text='The path to the converted file.', null=True)),
                ('stderr', models.TextField(blank=True, help_text='Stderr output from the conversion process.', null=True)),
                ('stdout', models.TextField(blank=True, help_text='Stdout output from the conversion process.', null=True)),
                ('has_warnings', models.BooleanField(help_text='If the conversion generated warnings then this should be True')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date/time the conversion was performed.')),
                ('meta', models.TextField(blank=True, help_text='Any extra arbitrary metadata about the conversion that might be useful. Should be JSON encoded.', null=True)),
            ],
        ),
    ]
