# Generated by Django 2.2.4 on 2019-09-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='original_filename',
            field=models.TextField(blank=True, help_text='If available, the name of the original file.', null=True),
        ),
    ]
