# Generated by Django 2.2.4 on 2019-09-11 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open', '0002_conversion_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Instead of deleting conversions, this flag should be set so a record still exists for feedback/analytics.'),
        ),
        migrations.AddField(
            model_name='conversion',
            name='source_format',
            field=models.TextField(default='', help_text='Format that was converted from.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversion',
            name='target_format',
            field=models.TextField(default='', help_text='Format that was converted to.'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ConversionFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='What the user has rated the feedback (1-5).')),
                ('comments', models.TextField(blank=True, help_text='Comments the user had regarding the conversion.', null=True)),
                ('email_address', models.EmailField(blank=True, help_text='Email address provided with feedback.', max_length=254, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date/time the feedback was created.')),
                ('conversion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback', to='open.Conversion')),
            ],
        ),
    ]
