# Generated by Django 2.2.4 on 2019-09-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stencila_open', '0003_auto_20190911_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='is_example',
            field=models.BooleanField(default=False, help_text="This Conversion is an example and so shouldn't be deleted."),
        ),
    ]
