# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 02:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(help_text='Package this build is for (e.g. cpp, r, docker)', max_length=32)),
                ('flavour', models.CharField(help_text='Flavour of the package (e.g. 3.2 for R package, ubuntu-14.04-r-3.2 for Docker image)', max_length=32)),
                ('version', models.CharField(help_text='Stencila version string', max_length=32)),
                ('commit', models.CharField(help_text='Stencila commit SHA', max_length=42)),
                ('platform', models.CharField(blank=True, help_text='Platform built for (e.g. linux/x86_64)', max_length=32, null=True)),
                ('url', models.TextField(blank=True, help_text='URL for the build file', null=True)),
                ('datetime', models.DateTimeField(blank=True, help_text='Date/time that this build was created', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='Builder', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
