# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 02:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.CharField(help_text='The id', max_length=64, primary_key=True, serialize=False)),
                ('spec', jsonfield.fields.JSONField(help_text='Flavour of the package (e.g. 3.2 for R package, ubuntu-14.04-r-3.2 for Docker image)')),
                ('datetime', models.DateTimeField(blank=True, help_text='Date/time that this snippet was created or updated', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User that last created or updated this snippet', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
