# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 06:05
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='spec',
            field=jsonfield.fields.JSONField(default='{}', help_text='Flavour of the package (e.g. 3.2 for R package, ubuntu-14.04-r-3.2 for Docker image)'),
        ),
    ]
