# Generated by Django 3.1.3 on 2020-11-20 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0010_auto_20201112_2256'),
        ('projects', '0021_auto_20201119_0526'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(help_text='The DOI string including both prefix and suffix e.g. 10.47704/stencila.54321', max_length=128)),
                ('url', models.URLField(help_text='The URL registered for the DOI. e.g. https://hub.stenci.la/doi/10.47704/stencila.54321')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date-time the DOI was created.')),
                ('deposited', models.DateField(blank=True, help_text='Date-time that the deposit request was sent to the registrar.', null=True)),
                ('deposit_request', models.JSONField(blank=True, help_text='JSON serialization of the deposit request sent to the registrar.', null=True)),
                ('deposit_response', models.JSONField(blank=True, help_text='JSON serialization of the deposit response received from the registrar.', null=True)),
                ('deposit_success', models.BooleanField(blank=True, help_text='Whether or not the deposit was successful.', null=True)),
                ('registered', models.DateField(blank=True, help_text='Date-time that a registration notification was received from the registrar.', null=True)),
                ('registration_response', models.JSONField(blank=True, help_text='The payload received from the registrar on notification.', null=True)),
                ('registration_success', models.BooleanField(blank=True, help_text='Whether or not the registration was successful.', null=True)),
                ('creator', models.ForeignKey(blank=True, help_text='The user who created the DOI.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dois_created', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, help_text='The job that registered the DOI.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doi_registered', to='jobs.job')),
                ('node', models.ForeignKey(help_text='The Stencila node that the DOI points to.', on_delete=django.db.models.deletion.PROTECT, related_name='dois', to='projects.node')),
            ],
        ),
    ]
