# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-12 02:11
from __future__ import unicode_literals

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of this account', max_length=256, unique=True)),
                ('personal', models.BooleanField(default=False, help_text='Is this a personal account?')),
                ('logo', models.ImageField(blank=True, help_text='Logo of account', max_length=1024, null=True, upload_to=accounts.models.account_logo_path)),
                ('gravatar_email', models.EmailField(blank=True, help_text='The email address used to retreive the account logo from gravatar.com', max_length=254, null=True)),
                ('hue', models.IntegerField(blank=True, help_text='Color hue used for this account.Degrees of color wheel: around 0 and 360 are reds, 120 greens, 240 blues.', null=True)),
                ('owners', models.ManyToManyField(help_text='The owners of this account', related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this account type.', max_length=24, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.ForeignKey(help_text='Type of this account', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounts.AccountType'),
        ),
    ]
