# Generated by Django 2.0.8 on 2018-09-13 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.TextField(blank=True, help_text='The name of the account (required).', null=True),
        ),
        migrations.AlterField(
            model_name='accountpermission',
            name='type',
            field=models.TextField(choices=[('MODIFY', 'modify'), ('ADMINISTER', 'administer')], help_text='Permissions to the Account: Administer or Modify (required).', unique=True),
        ),
        migrations.AlterField(
            model_name='accountrole',
            name='name',
            field=models.TextField(help_text='Roles which users can have assigned to the Account: Admin and Member (required).'),
        ),
        migrations.AlterField(
            model_name='accountrole',
            name='permissions',
            field=models.ManyToManyField(help_text='User Permissions to the Account: Administrator or Account Member.', related_name='roles', to='accounts.AccountPermission'),
        ),
        migrations.AlterField(
            model_name='team',
            name='account',
            field=models.ForeignKey(help_text='Account to which the Team is linked to. Each Team can be linked to only one account.', on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, help_text='Team description (optional).', null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(help_text='Team members. Each User can be a member of multiple Teams.', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.TextField(help_text='The name of the team (required).'),
        ),
    ]
