# Generated by Django 2.0.8 on 2018-09-27 22:30

from django.db import migrations, models
from django.db.models import Count


def populate_account_names(apps, schema_editor):
    """
    This migration changes `Account.name` to add a unique constraint and make it non null. This runs through each
    Account and makes sure it has a name and that is is unique.
    """
    Account = apps.get_model('accounts', 'Account')

    null_name_accounts = Account.objects.filter(name__isnull=True)

    for account in null_name_accounts:
        account.name = "Account (ID {})".format(account.pk)
        account.save()  # the unique constraint does not exist yet so do not yet need to check if name is unique

    while True:
        duplicates_found = False
        accounts = Account.objects.all().values('name', 'id').annotate(total=Count('name')).order_by('-total')

        for account_dict in accounts:
            if account_dict['total'] == 1:
                # Once we hit 1 there are no more duplicates. this might happen on first run if there are no duplicates
                break

            account = Account.objects.get(id=account_dict['id'])
            account.name = "{} (ID {})".format(account.name, account.pk)
            account.save()

            duplicates_found = True

        if not duplicates_found:
            """
            There is a small chance that the de-duplicated name will conflict with another name, take three accounts
            with names: 'Account A', 'Account A', 'Account A (ID 1)'. In this case the first 'Account A' conflicts so
            it will be renamed to 'Account A (ID 1). Which will then conflict with the last account, so the de-dupe must
            be run again to create 'Account A (ID 1) (ID 1)" (which hopefully won't conflict)
            """
            break


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0004_auto_20180913_0723'),
    ]

    operations = [
        migrations.RunPython(populate_account_names),
        migrations.AlterField(
            model_name='account',
            name='logo',
            field=models.ImageField(blank=True, help_text='A logo for the account', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.TextField(help_text='The name of the account (required).', unique=True),
        ),
    ]
