# Generated by Django 2.1.1 on 2018-10-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180928_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo for the account (optional). Please use an image that is 100 x 100 px or smaller. ', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.TextField(help_text='Name of the account (required).', unique=True),
        ),
    ]
