# Generated by Django 2.2.7 on 2019-11-14 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0004_2_1'),
        ('accounts', '0007_auto_20181120_0324'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.Account')),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='djstripe.Subscription')),
            ],
        ),
    ]
