# Generated by Django 2.2.7 on 2019-12-11 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0004_2_1'),
        ('accounts', '0009_auto_20191126_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowances', models.TextField(help_text='Allowances granted in JSON format.')),
                ('tag_line', models.TextField(help_text='A short tag line for the product.')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='extension', to='djstripe.Product')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductResourceAllowance',
        )
    ]
