# Generated by Django 2.2.7 on 2020-01-07 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20191211_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='slug',
            field=models.SlugField(blank=True, help_text='A unique identifier for the account, used in the URL.', null=True, unique=True),
        )
    ]
