# Generated by Django 2.2.7 on 2020-01-22 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200121_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='slug',
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.SlugField(help_text='Name of the account. Must be unique.', unique=True),
        ),
    ]
