# Generated by Django 2.2.7 on 2020-01-22 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200122_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='productextension',
            name='is_purchasable',
            field=models.BooleanField(default=True, help_text='Can this Produce be purchased, False means only can be bought with a coupon.'),
        ),
    ]
