# Generated by Django 2.2.7 on 2020-01-31 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200122_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo for the account. Please use an image that is 100 x 100 px or smaller. ', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='accountsubscription',
            name='subscription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='account', to='djstripe.Subscription'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, help_text='Team description', null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.TextField(help_text='Name of the team'),
        ),
    ]
