# Generated by Django 2.2.11 on 2020-04-26 18:15

from django.db import migrations, models

ACCOUNT_MEMBER_NAME = "member"
ACCOUNT_ADMIN_NAME = "admin"
ACCOUNT_VIEWER_NAME = "viewer"

MODIFY_PERMISSION = "modify"
ADMINISTER_PERMISSION = "administer"
VIEW_PERMISSION = "view"


def create_view_role(apps, schema_editor):
    """
    The VIEW role is new in this migration so add it to the DB.
    """

    AccountPermission = apps.get_model("accounts", "AccountPermission")
    AccountRole = apps.get_model("accounts", "AccountRole")

    # the AccountPermission Enum may have changed since this migration was created so hard code the permissions in here

    perm_cache = {}

    for permission_type in (VIEW_PERMISSION, MODIFY_PERMISSION, ADMINISTER_PERMISSION):
        perm, created = AccountPermission.objects.get_or_create(type=permission_type)
        perm_cache[permission_type] = perm

    role_map = (
        (ACCOUNT_VIEWER_NAME, (VIEW_PERMISSION,)),
        (ACCOUNT_MEMBER_NAME, (MODIFY_PERMISSION, VIEW_PERMISSION)),
        (
            ACCOUNT_ADMIN_NAME,
            (MODIFY_PERMISSION, ADMINISTER_PERMISSION, VIEW_PERMISSION),
        ),
    )

    for role_name, role_permissions in role_map:
        role, created = AccountRole.objects.get_or_create(name=role_name)

        if not created:
            role.permissions.clear()

        role.permissions.add(*[perm_cache[name] for name in role_permissions])

        role.save()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_auto_20200409_0040"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountpermission",
            name="type",
            field=models.TextField(
                choices=[
                    ("VIEW", "view"),
                    ("MODIFY", "modify"),
                    ("ADMINISTER", "administer"),
                ],
                help_text="An account permission type.",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="accountrole",
            name="name",
            field=models.TextField(
                help_text="The name of the account role e.g 'Account admin'"
            ),
        ),
        migrations.AlterField(
            model_name='accountrole',
            name='permissions',
            field=models.ManyToManyField(help_text='One or more account permissions that the role has e.g `ADMINISTER`.', related_name='roles', to='accounts.AccountPermission'),
        ),
        migrations.RunPython(create_view_role),
    ]
