# Generated by Django 2.2.12 on 2020-05-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo for the organisation. Please use an image that is 100 x 100 px or smaller.', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.SlugField(help_text='Name of the organisation. Must be unique.', unique=True),
        ),
        migrations.AlterField(
            model_name='accountrole',
            name='name',
            field=models.TextField(help_text="The name of the role e.g 'admin'"),
        ),
        migrations.AlterField(
            model_name='accountrole',
            name='permissions',
            field=models.ManyToManyField(help_text='One or more permissions that the role has e.g `ADMINISTER`.', related_name='roles', to='accounts.AccountPermission'),
        ),
    ]
