# Generated by Django 2.2.12 on 2020-05-27 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20200527_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(blank=True, help_text="When set, this is the user assigned to a 'personal' account.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
