# Generated by Django 2.0.7 on 2018-07-23 17:14

from django.db import migrations, models
import django.utils.timezone
import projects.models


class Migration(migrations.Migration):

    replaces = [('projects', '0002_auto_20180723_0004'), ('projects', '0003_auto_20180723_0245'), ('projects', '0004_auto_20180723_1708')]

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesprojectfile',
            name='modified',
            field=models.DateTimeField(blank=True, help_text='Time the file was last modified', null=True),
        ),
        migrations.AddField(
            model_name='filesprojectfile',
            name='name',
            field=models.CharField(default='unnamed', help_text='Name of the file (a path relative to the project root)', max_length=1024),
        ),
        migrations.AddField(
            model_name='filesprojectfile',
            name='size',
            field=models.IntegerField(blank=True, help_text='Size of the file in bytes', null=True),
        ),
        migrations.AddField(
            model_name='filesprojectfile',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Time this model instance was last updated'),
        ),
        migrations.AlterField(
            model_name='filesprojectfile',
            name='file',
            field=models.FileField(blank=True, help_text='The actual file stored', upload_to=projects.models.files_project_file_path),
        ),
        migrations.AlterUniqueTogether(
            name='filesprojectfile',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When this project was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='public',
            field=models.BooleanField(default=False, help_text='Should this project be publically visible?'),
        ),
    ]
