# Generated by Django 2.0.7 on 2018-07-23 02:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180723_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When this project was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='public',
            field=models.BooleanField(default=False, help_text='Should this project be publically visible?'),
        ),
    ]
