# Generated by Django 2.0.7 on 2018-07-23 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180723_0245'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filesprojectfile',
            unique_together=set(),
        ),
    ]
