# Generated by Django 2.0.8 on 2018-08-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180820_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.TextField(blank=True, help_text='The name of the project', null=True),
        ),
    ]
