# Generated by Django 2.0.8 on 2018-09-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20180903_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprojectrole',
            name='user',
        ),
        migrations.AlterField(
            model_name='project',
            name='sessions_concurrent',
            field=models.IntegerField(blank=True, help_text='Maximum number of sessions allowed to run at one time for this project (null = unlimited)', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='sessions_queued',
            field=models.IntegerField(blank=True, help_text='Maximum number of queued requests for a session for this project (null = unlimited)', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='sessions_total',
            field=models.IntegerField(blank=True, help_text='Maximum total number of sessions that can be created for this project (null = unlimited)', null=True),
        ),
        migrations.AlterField(
            model_name='userprojectrole',
            name='agent_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
