# Generated by Django 2.0.8 on 2018-09-05 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('projects', '0008_auto_20180905_2054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProjectRole',
            new_name='ProjectAgentRole',
        ),
    ]
