# Generated by Django 2.0.8 on 2018-09-13 07:23

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20180905_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time the request for a session was created.')),
                ('last_check', models.DateTimeField(auto_now=True, help_text='The last time that a client queried against this request')),
                ('environ', models.TextField(help_text='The environment in which to create the Session')),
                ('project', models.ForeignKey(help_text='The project this request is for', on_delete=django.db.models.deletion.CASCADE, related_name='session_requests', to='projects.Project')),
            ],
        ),
        migrations.AlterModelManagers(
            name='session',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='session',
            name='started',
            field=models.DateTimeField(help_text='DateTime this Session was started.', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='stopped',
            field=models.DateTimeField(help_text='DateTime this Session was stopped (or that we detected it had stopped).', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='url',
            field=models.URLField(db_index=True, help_text='URL for API access to administrate this Session'),
        ),
        migrations.AlterField(
            model_name='sessionparameters',
            name='name',
            field=models.TextField(blank=True, help_text='Names for the set of session parameters (optional). This can be used if you want to save a pre-set Session Parameters', null=True),
        ),
    ]
