# Generated by Django 2.1.2 on 2018-11-20 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_filesource'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubSource',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.Source')),
                ('repo', models.TextField(help_text='The Github repository identifier i.e. org/repo')),
                ('subpath', models.TextField(blank=True, help_text='Path to file or folder withing the repository', null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('projects.source',),
        ),
    ]
