# Generated by Django 2.1.2 on 2018-12-12 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_githubsource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together={('project', 'path')},
        ),
    ]
