# Generated by Django 2.1.5 on 2019-02-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_githubsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='execution_id',
            field=models.TextField(blank=True, help_text='The ID used to identify this session on the execution host (e.g. Docker container ID).', null=True),
        ),
    ]
