# Generated by Django 2.1.5 on 2019-02-13 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_session_execution_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.TextField(choices=[('SOURCE_PULL', 'SOURCE_PULL')])),
                ('started', models.DateTimeField(auto_now_add=True, help_text='DateTime this Event started.')),
                ('finished', models.DateTimeField(blank=True, help_text='DateTime this Event finished. If null assume it is still running.', null=True)),
                ('message', models.TextField(blank=True, help_text='A message associated with this Event, may be an error message or some information or blank.', null=True)),
                ('success', models.BooleanField(blank=True, help_text='Indicates if the event finished with success or not. If the Event is still in progress then success will be null.', null=True)),
                ('project', models.ForeignKey(help_text='The Project that this Event is for.', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.Project')),
            ],
        ),
    ]
