# Generated by Django 2.1.5 on 2019-02-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_projectevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectevent',
            options={'ordering': ['-started']},
        ),
        migrations.AddField(
            model_name='session',
            name='client_class_id',
            field=models.TextField(blank=True, help_text='The ID of the client class that created this session.', null=True),
        ),
        migrations.AlterField(
            model_name='projectevent',
            name='event_type',
            field=models.TextField(choices=[('SOURCE_PULL', 'SOURCE_PULL'), ('ARCHIVE', 'ARCHIVE')]),
        ),
    ]
