# Generated by Django 2.1.5 on 2019-03-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20190226_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.TextField(help_text='The name of the project', null=True),
        ),
    ]
