# Generated by Django 2.1.5 on 2019-04-18 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20190319_0251'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDocsSource',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.Source')),
                ('doc_id', models.TextField(help_text="Google's ID of the document.")),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('projects.source',),
        ),
    ]
