# Generated by Django 2.1.5 on 2019-05-21 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_googledocssource'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='main_file_path',
            field=models.TextField(blank=True, help_text='The path to the main file of the Project. Does not need to be set.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='main_file_source',
            field=models.ForeignKey(blank=True, help_text="If the Project's main file is inside a linked Source, this is its id.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_file_project', to='projects.Source'),
        ),
    ]
