# Generated by Django 2.2.7 on 2019-12-13 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20190521_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(help_text='The path to the published file (in HTML format).')),
                ('slug', models.SlugField(help_text='Slug to be used in HTML.')),
                ('project', models.OneToOneField(help_text='Project this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='published_item', to='projects.Project')),
            ],
        ),
    ]
