# Generated by Django 2.2.7 on 2019-12-19 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20191213_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlSource',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.Source')),
                ('url', models.URLField(help_text='The URL of the remote file.')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('projects.source',),
        ),
    ]
