# Generated by Django 2.2.7 on 2020-01-19 23:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20200107_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisheditem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date/time the item was first published.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisheditem',
            name='source',
            field=models.ForeignKey(help_text='The source item of this publication. May be null for a DiskSource.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.Source'),
        ),
        migrations.AddField(
            model_name='publisheditem',
            name='source_path',
            field=models.TextField(blank=True, help_text='The path of the file that was published. May be null/blank for sources like URLs where we just fetch the content.', null=True),
        ),
        migrations.AddField(
            model_name='publisheditem',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='The date/time the item was last published.'),
        ),
        migrations.AddField(
            model_name='publisheditem',
            name='url_path',
            field=models.TextField(default='', help_text='The path used to access the published item on the web, relative to the account/project.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publisheditem',
            name='path',
            field=models.TextField(help_text='The relative path to the published file (in HTML format). Relative to the published item storage directory.'),
        ),
        migrations.AlterField(
            model_name='publisheditem',
            name='project',
            field=models.ForeignKey(help_text='Project this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='published_items', to='projects.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='publisheditem',
            unique_together={('project', 'url_path')},
        ),
        migrations.RemoveField(
            model_name='publisheditem',
            name='slug',
        ),
    ]
