# Generated by Django 2.2.7 on 2020-01-20 03:07

from django.db import migrations, models
import projects.validators


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20200119_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisheditem',
            name='path',
            field=models.TextField(blank=True, help_text='The relative path to the published file (in HTML format). Relative to the published item storage directory.', null=True),
        ),
        migrations.AlterField(
            model_name='publisheditem',
            name='url_path',
            field=models.TextField(help_text='The path used to access the published item on the web, relative to the account/project.', validators=[projects.validators.validate_publish_url_path]),
        ),
    ]
