# Generated by Django 2.2.7 on 2020-01-21 21:32

from django.db import migrations, models




class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20200121_2043'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE projects_project SET name=slug"
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.TextField(help_text="Name of the project, an identifier used in URLs. Must be unique within the Project's account"),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'account'), ('slug', 'account')},
        ),
    ]
