# Generated by Django 2.2.7 on 2020-01-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('projects', '0027_auto_20200121_2157'), ('projects', '0028_auto_20200121_2206')]

    dependencies = [
        ('projects', '0026_auto_20200121_2132'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'account')},
        ),
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.SlugField(help_text="Name of the project, an identifier used in URLs. Must be unique within the Project's account"),
        ),
    ]
