# Generated by Django 2.2.7 on 2020-01-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_auto_20200121_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.SlugField(help_text="Name of the project, an identifier used in URLs. Must be unique within the Project's account"),
        ),
    ]
