# Generated by Django 2.2.7 on 2020-01-31 08:12

from django.db import migrations


def remove_non_sourcepath_published_items(apps, schema_editor):
    """This removes PublishedItems without a source_path. This should only be ones that have failed conversion."""

    PublishedItem = apps.get_model('projects', 'PublishedItem')

    PublishedItem.objects.filter(source_path__isnull=True).delete()
    PublishedItem.objects.filter(source_path='').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0027_auto_20200121_2157_squashed_0028_auto_20200121_2206'),
    ]

    operations = [
        migrations.RunPython(remove_non_sourcepath_published_items)
    ]
