# Generated by Django 2.2.7 on 2020-01-31 08:17

from django.db import migrations, models
import projects.validators


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_auto_20200131_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubsource',
            name='subpath',
            field=models.TextField(blank=True, help_text='Path to file or folder within the repository', null=True),
        ),
        migrations.AlterField(
            model_name='publisheditem',
            name='source_path',
            field=models.TextField(help_text='The path of the file that was published.'),
        ),
        migrations.AlterField(
            model_name='publisheditem',
            name='url_path',
            field=models.TextField(blank=True, help_text='The path used to access the published item on the web, relative to the account/project.', null=True, validators=[projects.validators.validate_publish_url_path]),
        ),
    ]
