# Generated by Django 2.2.7 on 2020-01-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_auto_20200131_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisheditem',
            name='path',
            field=models.TextField(blank=True, help_text='The full path to the published file (in HTML format).', null=True),
        ),
    ]
