# Generated by Django 2.2.7 on 2020-02-04 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20200131_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(help_text="The path on disk to the snapshot. Will be blank/null if the snapshot operation hasn't been performed yet.")),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date/time the Snapshot instance was created.')),
                ('snapshot_time', models.DateTimeField(blank=True, help_text='The time that Snapshot operation happened, null if the snapshot has not yet been performed.', null=True)),
                ('version_number', models.PositiveIntegerField(verbose_name='Each snapshot should have an incremental version.')),
                ('tag', models.SlugField(blank=True, help_text='A tag to identify the snapshot easily. Must be unique for the project.', null=True)),
                ('project', models.ForeignKey(help_text='Project this snapshot belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='projects.Project')),
            ],
            options={
                'unique_together': {('project', 'version_number'), ('project', 'tag')},
            },
        ),
    ]
