# Generated by Django 2.2.7 on 2020-02-04 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200131_0817'),
        ('projects', '0031_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='snapshot_in_progress',
            field=models.BooleanField(default=False, help_text='Should be set true when a Snapshot begins for a project.'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='path',
            field=models.TextField(help_text='The path to the snapshot directory on disk.'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'account'), ('id', 'snapshot_in_progress')},
        ),
    ]
