# Generated by Django 2.2.10 on 2020-02-20 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_auto_20200204_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisheditem',
            name='snapshot',
            field=models.ForeignKey(blank=True, help_text='The snapshot that contains the original source. Null for PublishedItems created from non-snapshot files.', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Snapshot'),
        ),
    ]
