# Generated by Django 2.2.10 on 2020-02-21 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0033_publisheditem_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectevent',
            name='level',
            field=models.IntegerField(choices=[('EMERGENCY', 0), ('ALERT', 1), ('CRITICAL', 2), ('ERROR', 3), ('WARNING', 4), ('NOTICE', 5), ('INFORMATIONAL', 6), ('DEBUG', 7)], default=6, help_text='The "log level" of the event.'),
        ),
        migrations.AddField(
            model_name='projectevent',
            name='log',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=dict, help_text='Log messages, in the DB they are stored as text but are automatically JSON (de)serialized on writing/reading.', null=True),
        ),
        migrations.AddField(
            model_name='projectevent',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who performed/triggered this event.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectevent',
            name='event_type',
            field=models.TextField(choices=[('SOURCE_PULL', 'SOURCE_PULL'), ('ARCHIVE', 'ARCHIVE'), ('SNAPSHOT', 'SNAPSHOT')]),
        ),
        migrations.AlterField(
            model_name='publisheditem',
            name='source_path',
            field=models.TextField(help_text='The relative path of the file that was published. Relative to its Project or snapshot root.'),
        ),
    ]
