# Generated by Django 2.2.10 on 2020-03-04 02:52

from django.db import migrations, models
import jsonfallback.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_auto_20200221_0253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectevent',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterField(
            model_name='projectevent',
            name='event_type',
            field=models.TextField(choices=[('SOURCE_PULL', 'SOURCE_PULL'), ('ARCHIVE', 'ARCHIVE'), ('SNAPSHOT', 'SNAPSHOT'), ('CONVERT', 'CONVERT')]),
        ),
        migrations.CreateModel(
            name='RpcTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_host', models.TextField(help_text='The host that generated the request. May be a FQDN or simple identifying string.')),
                ('response_host', models.TextField(blank=True, help_text="THe host that response to the request (generated the response). May be a FQDN or simple identifying string, or null if the Transaction hasno response (e.g. it's a notification).", null=True)),
                ('transaction_id', models.TextField(blank=True, help_text='The transaction ID, used to link together the request and response.Should be unique for the request_host. Will be null for notification requests.', null=True)),
                ('method', models.TextField(blank=True, help_text='The JSON RPC method (from the request).', null=True)),
                ('params', jsonfallback.fields.FallbackJSONField(blank=True, help_text='The JSON RPC params (from the request).', null=True)),
                ('result', jsonfallback.fields.FallbackJSONField(blank=True, help_text='The JSON RPC result (from the response).', null=True)),
                ('error', jsonfallback.fields.FallbackJSONField(blank=True, help_text='The JSON RPC error (from the response). Usually null.', null=True)),
                ('request_time', models.DateTimeField(blank=True, help_text='The date/time the request to record the request was received.', null=True)),
                ('response_time', models.DateTimeField(blank=True, help_text='The date/time the request to record the response was received.', null=True)),
                ('transport', models.TextField(help_text='The transport over which the transaction was communicated. E.g. ws, tcp:3000, https:443, etc.')),
            ],
            options={
                'unique_together': {('request_host', 'transaction_id')},
            },
        ),
    ]
