# Generated by Django 2.2.10 on 2020-03-21 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_auto_20200221_0253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectevent',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterField(
            model_name='project',
            name='account',
            field=models.ForeignKey(help_text='Account that the project is linked to.', on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='When the project was created.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(help_text='User who created the project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the project.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.SlugField(help_text="Name of the project. Used as an identifier in URLs. Must be unique within the project's account."),
        ),
        migrations.AlterField(
            model_name='project',
            name='public',
            field=models.BooleanField(default=False, help_text='Is the project be publicly visible?'),
        ),
        migrations.AlterField(
            model_name='projectevent',
            name='event_type',
            field=models.TextField(choices=[('SOURCE_PULL', 'SOURCE_PULL'), ('ARCHIVE', 'ARCHIVE'), ('SNAPSHOT', 'SNAPSHOT'), ('CONVERT', 'CONVERT')]),
        ),
    ]
