# Generated by Django 2.2.11 on 2020-03-25 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_auto_20200321_0231'),
        ('projects', '0035_auto_20200304_0252'),
    ]

    operations = [
    ]
