# Generated by Django 2.2.11 on 2020-03-31 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_auto_20200321_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisheditem',
            name='source',
            field=models.ForeignKey(help_text='The source item of this publication. May be null for a DiskSource.', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Source'),
        ),
    ]
