# Generated by Django 2.2.11 on 2020-04-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0036_auto_20200331_0828"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="path",
            field=models.TextField(
                default=".",
                help_text="The path that the file or directory from the source is mapped to in the Project",
            ),
        ),
    ]
