# Generated by Django 2.2.12 on 2020-04-05 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfallback.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0036_auto_20200331_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the project was created.')),
                ('app', models.TextField(blank=True, help_text='An identifier for the app that created the node.', null=True)),
                ('host', models.URLField(blank=True, help_text='URL of the host document within which the node was created.', null=True)),
                ('key', models.TextField(db_index=True, help_text='The key to the node')),
                ('json', jsonfallback.fields.FallbackJSONField(help_text='The JSON content of node.')),
                ('creator', models.ForeignKey(blank=True, help_text='User who created the project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='The project this node is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='projects.Project')),
            ],
            options={
                'unique_together': {('project', 'key')},
            },
        ),
    ]
