# Generated by Django 2.2.11 on 2020-04-03 07:09

from django.db import migrations, models
import django.db.models.deletion
import jsonfallback.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_auto_20200331_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.TextField(blank=True, help_text='An identifier for the app that created the node.', null=True)),
                ('host', models.URLField(blank=True, help_text='URL of the host document within which the node was created.', null=True)),
                ('key', models.TextField(db_index=True, help_text='The key to the node')),
                ('json', jsonfallback.fields.FallbackJSONField(help_text='The JSON content of node.')),
                ('project', models.ForeignKey(help_text='The project this node is associated with.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='nodes', to='projects.Project')),
            ],
            options={
                'unique_together': {('project', 'key')},
            },
        ),
    ]
