# Generated by Django 2.2.12 on 2020-04-06 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_node'),
        ('projects', '0037_auto_20200405_2328'),
    ]

    operations = [
    ]
