# Generated by Django 2.2.12 on 2020-04-07 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0038_merge_20200406_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snapshot',
            old_name='snapshot_time',
            new_name='completed'
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='completed',
            field=models.DateTimeField(blank=True, help_text='The date/time the snapshot was completed; null if the snapshot has not yet been started.', null=True),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='creator',
            field=models.ForeignKey(help_text='The user who created the snapshot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date/time the snapshot was created.'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='project',
            field=models.ForeignKey(help_text='The project this snapshot belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='tag',
            field=models.SlugField(blank=True, help_text='A tag to identify the snapshot easily.Must be unique for the project.', null=True),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='version_number',
            field=models.PositiveIntegerField(help_text='The sequential number of the snapshot within the project.'),
        ),
    ]
