# Generated by Django 2.2.12 on 2020-05-25 07:00

from django.db import migrations, models
import projects.source_models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_elifesource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=projects.source_models.NON_POLYMORPHIC_CASCADE, related_name='sources', to='projects.Project'),
        ),
    ]
