# Generated by Django 2.2.12 on 2020-05-26 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_auto_20200525_0700'),
        ('projects', '0044_googledrivesource'),
    ]

    operations = [
    ]
