# Generated by generate.js. Commit this file, but do not edit it.

from manager.helpers import EnumChoice

# The version of Thema to use
version = "2.10.4"


class Themes(EnumChoice):
    """The list of Thema themes."""

    bootstrap = "bootstrap"
    elife = "elife"
    galleria = "galleria"
    latex = "latex"
    nature = "nature"
    plos = "plos"
    rpng = "rpng"
    skeleton = "skeleton"
    stencila = "stencila"
    tufte = "tufte"
    wilmore = "wilmore"
