# Generated by Django 2.0.7 on 2018-07-18 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='url',
        ),
    ]
